#!lua name=mylib2
--- 2023-12-1 15:01:10
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tt.
--- DateTime: 2023/11/8 14:26
---
------------------------------------------------------------------------
----------------------------user messages-------------------------------
local function save_user_msg(keys, args)
    local uid = keys[1]
    local msgId = args[1]
    local msg = args[2]

    redis.call('SET', "umsg:{" .. uid .. "}:" .. msgId, msg, 'EX', 3600)
end
local function save_user_msg2(keys, args)
    local uid = keys[1]
    local msgId = args[1]
    local msg = args[2]

    redis.call('SET', "umsg:{" .. uid .. "}:" .. msgId, msg, 'EX', 3600)
end

redis.register_function('save_user_msg', save_user_msg)
redis.register_function('save_user_msg2', save_user_msg2)
